import { Poppins, Playfair_Display } from "next/font/google";
import "./globals.css";
import { Roboto } from "next/font/google";
import Header from "@/components/global/header/Header";
import Footer from "@/components/global/footer/Footer";

const poppins = Poppins({
  subsets: ["latin"],
  weight: ["300", "400", "500", "600", "700"],
  variable: "--font-poppins",
});

const playfair = Playfair_Display({
  subsets: ["latin"],
  weight: ["600", "700"],
  variable: "--font-playfair",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${poppins.variable} ${playfair.variable} font-sans bg-gray-50 text-gray-800 antialiased selection:bg-primary_color selection:text-white`}>
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}
